version: '3.7'

services:
  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
      args:
        license_key: ${MAXMIND_LICENSE_KEY}
    init: true
    container_name: sqlserver
    ports:
      - "5434:1433"